language: node_js
node_js:
    - "4"
    - "6"

before_script:

script:
    - npm run lint
    - npm test

after_success:
    - npm install istanbul codecov
    - NODE_ENV=cov ./node_modules/.bin/istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec
    - cat ./coverage/coverage.json | ./node_modules/.bin/codecov

sudo: false
