language: node_js
node_js:
    - "4"
    - "6"

before_script:

script:
    - npm run lint
    - npm test

after_success:
    - npm install istanbul codecov blanket
    - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- -R spec
    - ./node_modules/.bin/codecov

sudo: false
