language: node_js
node_js:
    - "4"
    - "6"

before_script:

script:
    - npm run lint
    - npm test

after_success:
    - npm install istanbul codecov.io
    - ./node_modules/istanbul/lib/cli.js cov run_tests
    - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js

sudo: false
