name: Tests

on: [ push ]

jobs:

  ci-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node-version:
          - 12
          - 14
          - 16
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install
    - run: npm test
      env:
        CI: true
