
name: Tests

on: [ push ]

env:
  CI: true
  NODE_OPTIONS: --max-old-space-size=1536

jobs:

  ci-test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest windows-latest ]
        node-version: [ 14.x, 16.x ]
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
      name: Checkout Module
      with:
        fetch-depth: 1

    - uses: actions/setup-node@v2
      name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm install

    - name: Run test suite
      run: npm run test
